routes/admin.py
from flask import Blueprint, render_template, request, redirect, flash, url_for
from models import db, User, LoginManager, Bcrypt, Listing, ListingTransaction, pytz, current_user

admin = Blueprint("admin", __name__, static_folder="static", template_folder="templates")


@admin.route("/panel")
def adminPanel():
    if not current_user.is_authenticated:
        flash("kur lien?",'error')
        return redirect(url_for("home.index"))
    if not current_user.isAdmin:
        flash("kur mēģini ielīst mazais? :D",'error')
        return redirect(url_for('home.index'))
    return render_template("/admin/selection.html")


@admin.route("/view/users")
def view_users():
    if not current_user.isAdmin:
        flash("kur mēģini ielīst mazais? :D",'error')
        return redirect(url_for('home.index'))
    
    return render_template("/admin/view_users.html", users = User.query.all())


@admin.route("/user/delete/<int:id>",methods=["POST"])
def delete_users(id):
    if not current_user.isAdmin:
        flash("Oi oi oi... tu uzmanīgāk",'error')
        return redirect(url_for("home.index"))
    user = User.query.filter_by(id=id).first()
    if current_user == user:
        flash("Tu nevari dzēst pats sevi.. wtf vecīt? :D viss kārtībā?",'error')
        return redirect(url_for("admin.view_user",id=id))
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("admin.view_users"))
    
@admin.route("/view/user/<int:id>")
def view_user(id):
    if not current_user.isAdmin:
        flash("PARASTIE MIRSTĪGIE NEDRĪKST APSKATĪT",'error')
        return redirect(url_for("home.index"))
    user = User.query.filter_by(id=id).first()
    if not user:
        return ('', 204)
    return render_template("/admin/view_user.html", user = user)


@admin.route("/update_user/<int:id>", methods=["POST"])
def update_user(id):
    if not current_user.isAdmin:
        flash("Tev nebūs mainīt lietotājus!",'error')
        return redirect(url_for("home.index"))
    user = User.query.filter_by(id=id).first()
    errors = 0
    username = request.form["username"]
    name = request.form["name"]
    if User.query.filter_by(username=username).first():
        if not username == current_user.username:
            flash("Nevar 2 lietotājiem būt 1 lietotājvārds! :D","error")
        errors += 1
    
    if errors > 0:
        return redirect(url_for("admin.view_user",id=id))
    user.username = username
    user.name = name
    db.session.commit()
    flash("veiksmīgi rediģēts lietotājs!",'success')
    return redirect(url_for("admin.view_user",id=id))

@admin.route("/user/give_admin/<int:id>", methods=['POST'])
def giveAdmin(id):
    if not current_user.isAdmin:
        flash('parastajam mirstīgajam nav šādas tiesības..','error')
        return redirect(url_for("home.index"))
    if current_user.id == id:
        flash('nevar pats sev iedot adminu :D!','error')
        return redirect(url_for("admin.view_user",id=id))
    
    user = User.query.filter_by(id=id).first()
    user.isAdmin = True
    db.session.commit()
    message = 'veiksmīgi iedevi admina tiesības lietotājam ar id',str(id)
    flash(message,'success')
    return redirect(url_for("admin.view_user",id=id))

@admin.route("/user/take_admin/<int:id>",methods=['POST'])
def takeAdmin(id):
    if not current_user.isAdmin:
        flash('parastajam mirstīgajam nav šādas tiesības..','error')
        return redirect(url_for("home.index"))
    if current_user.id == id:
        flash('nevar pats sev noņemt adminu :D!','error')
        return redirect(url_for("admin.view_user",id=id))

    user = User.query.filter_by(id=id).first()
    user.isAdmin = False
    db.session.commit()
    message = 'veiksmīgi noņēmi admina tiesības lietotājam ar id',str(id)
    flash(message,'success')
    return redirect(url_for("admin.view_user",id=id))

@admin.route("/prece/<int:id>")
def preceAdmin(id):
    if not current_user.is_authenticated:
        return redirect(url_for('home.index'))
    if not current_user.isAdmin:
        flash('Tikai daži izredzētie var šeit iet','error')
        return redirect(url_for('home.index'))
    
    return render_template("admin/view_listing.html")

@admin.route("/preces")
def precesAdmin():
    if not current_user.is_authenticated:
        return redirect(url_for('home.index'))
    if not current_user.isAdmin:
        flash('Tikai daži izredzētie var šeit iet','error')
        return redirect(url_for('home.index'))
    
    return render_template("admin/view_listings.html", listings=Listing.query.filter(Listing.auctionStatus.notin_([2,3])).all())


@admin.route("/transakcijas")
def transakcijas():
    if not current_user.is_authenticated:
        return redirect(url_for('home.index'))
    if not current_user.isAdmin:
        flash('TU NEESI DAĻA NO DIEVIEM!', 'error')
        return redirect(url_for('home.index'))
    transactions = ListingTransaction.query.filter_by(winner=True).all()
    listings = []
    for transaction in transactions:
        listings.append(Listing.query.filter_by(id=transaction.listingID).first())
    return render_template("admin/view_transactions.html", transactions = transactions, listings=listings)

@admin.route("/transakcija/<string:bankdescription>")
def transakcija(bankdescription):
    if not current_user.is_authenticated:
        return redirect(url_for('home.index'))
    if not current_user.isAdmin:
        flash('TU NEESI DAĻA NO DIEVIEM!', 'error')
        return redirect(url_for('home.index'))
    transactions = ListingTransaction.query.filter(ListingTransaction.bankDescription.contains(bankdescription)).all()
    listings = []
    for transaction in transactions:
        listings.append(Listing.query.filter_by(id=transaction.listingID).first())
    return render_template("admin/view_transactions.html", transactions = transactions, listings=listings)

@admin.route("/set_paid_statuss/<int:id>")
def transaction_paid_statuss(id):
    if not current_user.is_authenticated:
        return redirect(url_for('home.index'))
    if not current_user.isAdmin:
        flash("TEV NAV VARA ŠEIT", 'error')
        return redirect(url_for("home.index"))
    
    transaction = ListingTransaction.query.filter_by(id=id).first()
    if transaction.paid:
        transaction.paid = False
    else:
        transaction.paid = True
    db.session.commit()
    return redirect(url_for('admin.transakcijas'))

routes/home.py
from flask import Blueprint, render_template
from flask_login import current_user
from models import Listing, pytz
import math
home = Blueprint("home", __name__, static_folder="static", template_folder="templates")




@home.route("/home")
@home.route("/")
@home.route("/izsoles/<int:page>")
def index(page=1):
    page -= 1
    return render_template('home.html', 
                           listings=Listing.query.filter(Listing.auctionStatus.notin_([2,3])).order_by(Listing.auctionTime.asc()).offset(page*6).limit(6).all(),
                           page=page,
                           pageAmount=math.ceil(Listing.query.filter(Listing.auctionStatus.notin_([2,3])).count()/6)+1,
                           )

@home.route("/noteikumi")
def rules():
    return render_template('rules.html')

templates/home.html
{% extends 'template.html' %}


<!-- title -->

{% block title %} 

    {% if listings %}
    Izsoles
    {% endif %}

{% endblock %}

{% block izsoles %}active{% endblock %}

{% block heading %}

<style>
    a
    {
        text-decoration: none;
        color: #ADA8BE;
    }
    .listing
    {
        background-color: transparent;
        width: 80%;
        height: 256px;
        margin-top: 5%;
        height: 150%;
    }

    hr
    {
        border-bottom:none;
        border-left: none;
        border-right: none;
        border-top-width: 3px;
        border-top-color: black;
        background-color: black;
    }

    .listingImage
    {
        float: left; 
        width: 256px;
    }

    .listingInfo
    {
        overflow: hidden; 
        padding-left: 2vw;
        padding-bottom: 1vh;
        text-align:left;
        text-decoration: none;
    }
    .name {
        margin-top: 0px;
    }
    .startPrice
    {
        color: #A28497;
        text-decoration: none;
    }

    .priceIncrease
    {
        color: #A28497;
        text-decoration: none;
    }

    .auctionDate
    {
        color: #A28497; 
        text-decoration: none;
    }

    .info
    {
        color: #A28497;
        text-decoration: none;  
    }

    .description
    {
        word-break:keep-all;
        padding-bottom: 5px;
        border-bottom: 1px solid rgb(150, 150, 150);
    }
    .joinAuction
    {
        padding: 15px;
        margin-top: 10px;
        width: fit-content;
        background-color:#4267B2;
        color: white;
    }
    .joinAuction:hover
    {
        background-color:#1d489e;
    }
    .joinAuction:active
    {
        background-color:#0e388b;
    }
    .overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
      }
      
      .listing-info {
        background-color: white;
        padding: 20px;
        border-radius: 5px;
        text-align: center;
        width: 90vw;
        min-height: 50%;
      }
</style>

{% endblock %}

<!-- content -->

{% block content %} 
    
<center>
    {% if not listings %}
     <h2>Nav publicēta neviena izsole!</h2>
        {% if current_user.name %}
            <h3>Publicē savējo
                <a style="color:#0645AD;"href="{{url_for('listing.new')}}">šeit!</a>
            </h3>
        {% else %}
            <h3>
                <a style="color:#0645AD;" href="{{url_for('auth.register')}}">Pievienojies</a>
                 un publicē savējo!
            </h3>
        {% endif %}
    {% endif %}
    {% for number in range(1, pageAmount) %}
        {% if number == page + 1 %}
            <a style="color:#691069; text-decoration: underline;" href="/izsoles/{{number}}">{{number}}</a>
        {% else %}
            <a href="/izsoles/{{number}}">{{number}}</a>
        {% endif %}
    {% endfor %}
    {% for listing in listings %}
        <a id="listing{{listing.id}}">
            <div class="listing">
                <div class="listingImage">
                    <img 
                    src="{{listing.image}}" 
                    id="image{{listing.id}}"
                    width= "256px"
                    height = "256px"
                    style="object-fit: cover;">
                </div>
                <div class="listingInfo">
                    <h1 class="name" id="name{{listing.id}}">{{listing.name}}</h1>
                    
                    {% if listing.description|length > 50 %}
                        <h3 class="description" id="description{{listing.id}}">{{listing.description[:50]}} ...</h3>
                    {% else %}
                        <h3 class="description" id="description{{listing.id}}">{{listing.description[:50]}}</h3>
                    {% endif %}       
                    <h3><span class="info">Sākuma cena: </span><span class="startPrice" id="startPrice{{listing.id}}">{{listing.startPrice}}</span></h3>
                    <h3><span class="info">Cenas kāpums: </span><span class="priceIncrease" id="priceIncrease{{listing.id}}">{{listing.priceIncrease}}</span></h3>
                    <h3><span class="Date">Izsoles laiks: {{listing.auctionTime}}</span></h3>
                    <h3><span class="info">Izsoles statuss:     
                    </span><span class="auctionDate" id="auctionStatus{{listing.id}}">
                        {% if listing.auctionStatus == 0 %}
                            izsole gaida
    
                        {% elif listing.auctionStatus == 1 %}
                            izsole sākas
                        {% elif listing.auctionStatus == 2 %}
                            Izsole sākusies
                        {% else %}
                            izsole beidzās
                        {% endif %}
                    </span></h3><br>
                </div>
            </div>
        </a> <br>
    {% endfor %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            {% for listing in listings %}
                document.getElementById("listing{{listing.id}}").addEventListener("click", function() {
                    var overlay = document.createElement("div");
                    overlay.id = "overlay{{listing.id}}";
                    overlay.classList.add("overlay");
    
                    var listingInfo = document.createElement("div");
                    listingInfo.classList.add("listing-info");
    

    
                    // Listing name
                    var listingName = document.createElement("h1");
                    listingName.classList.add("name");
                    listingName.textContent = "{{listing.name}}";
                    listingInfo.appendChild(listingName);
    
                    // Listing description
                    var listingDescription = document.createElement("h3");
                    listingDescription.classList.add("description");
                    listingDescription.textContent = "{{listing.description}}";
                    listingInfo.appendChild(listingDescription);
    
                    // Listing image
                    var listingImage = document.createElement("img");
                    listingImage.src = "{{listing.image}}";
                    listingImage.style.width = "30%";
                    listingImage.style.objectFit = "cover";
                    listingInfo.appendChild(listingImage);

                    {% if current_user.id == listing.userID or current_user.isAdmin %}
                        var br = document.createElement("br");
                        listingInfo.appendChild(br);


                        var link = document.createElement("a");
                        link.href = "/prece/rediget/{{listing.id}}";
                        link.textContent = "rediģēt";
                        listingInfo.appendChild(link);  
                    {% endif %}

                    overlay.appendChild(listingInfo);
                    document.body.appendChild(overlay);
    
                    overlay.addEventListener("click", function(e) {
                        if (e.target === overlay) {
                            document.body.removeChild(overlay);
                        }
                    });
                });
            {% endfor %}
        });
    </script>
    
    <div style="margin-top: 5%;">
        {% for number in range(1, pageAmount) %}
            {% if number == page + 1 %}
                <a style="color:#691069; text-decoration: underline;" href="/izsoles/{{number}}">{{number}}</a>
            {% else %}
                <a href="/izsoles/{{number}}">{{number}}</a>
            {% endif %}
        {% endfor %}
    </div>
</center>

    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js" integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function() {
    setInterval(function() {
        $.ajax({
        url: "prece/db/refresh/get/{{page}}",
        type: "GET", 
        success: function(data) {
             $.each(data, function(index, listing) {
            var row = $("div[data-id='" + listing.id + "']");
            var username = '{{current_user.username}}';
            var id = '{{current_user.id}}';
            if(document.getElementById("name"+listing.ident)){
                document.getElementById("name"+listing.ident).innerHTML = listing.name;
                document.getElementById("image"+listing.ident).src = listing.image;
                if(listing.auctionStatus === 0)
                {
                    document.getElementById('auctionStatus'+listing.ident).innerHTML = "izsole gaida";
                }
                else if(listing.auctionStatus === 1)
                {
                    console.log("{{current_user.is_authenticated}}");   
                    if(username)
                    {
                        if(Number(id) === Number(listing.user))
                        {
                            document.getElementById("auctionStatus"+listing.ident).innerHTML = "izsole sākas";
                        }
                        else
                        {
                            document.getElementById("auctionStatus"+listing.ident).innerHTML = "izsole sākas <a href='/prece/pievienoties/"+listing.ident+"'><div class='joinAuction'>Pievienoties izsolei</div></a><br>";
                        }
                    }
                    else
                    {
                        document.getElementById("auctionStatus"+listing.ident).innerHTML = "izsole sākas";
                    }
                }
                else if(listing.auctionStatus === 2)
                {
                    var element = document.getElementById("listing"+listing.ident);
                    element.remove();
                    document.getElementById("auctionStatus"+listing.ident).innerHTML = "izsole sākusies";
                }
                else
                {
                    var element = document.getElementById("listing"+listing.ident);
                    element.remove();
                    document.getElementById("auctionStatus"+listing.ident).innerHTML = "izsole beidzās";
                };
            }   
            });
        }
        });
    }, 1000);
    });
</script>
{% endblock %}

templates/rules.html
{% extends 'template.html' %}
{% block title %}Mājaslapas lietošanas noteikumi!{% endblock %}

{% block content %} 

{% endblock %}

templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=1920px, initial-scale=1.0">
    <title>Document</title>
    {% block heading %} {% endblock %}


    
    <style>

        body 
        {
            font-family: Arial;
            padding: 0px;
            margin: 0px;
            background-color: #4A5240;
            color: #ADA8BE;
            min-width: 100vw;
            margin: 0 auto;
            overflow: auto;
        }
        @media screen and (min-width: 601px) {
            link {
                font-size: 4vw;
            }
            lineleft {
                font-size: 4vw;
            }
            profileInfo {
                font-size: 4vw;
            }
        }

        @media screen and (max-width: 600px) {
            link {
                font-size: 6vw;
            }
            linkleft {
                font-size: 6vw;
            }
            profileInfo {
                font-size: 6vw;
            }
        }

        a.active {
            font-weight:550;
            color:rgb(155, 81, 174);
        }

        .website
        {
            margin: 10vw;
            margin-top: 30px;
        
        }
        
        .navigation
        {
            margin-top: 1vh;
            padding: 50px;
            background-color:#6F5E5C;
        }
        
        .content
        {
            background-color:#6F5E5C;
            min-height: 60vh;
            margin-top: 4vh;
            padding: 8px;
        }
        
        .link
        {
            
            text-decoration: underline;
            vertical-align: top;
            color:#A28497;
            margin-right: 20px;
        } 
        .linkleft
        {
            text-decoration: underline;
            vertical-align: top;
            float:right;
            color:#A28497;
            margin-left: 20px;
        } 
        .profileInfo
        {
            vertical-align: top;
            float:right;
            color:#C6CAED;
            margin-left: 20px;
            
        }


        .flash 
        {
            position: fixed;    
            left: 50%;
            bottom: 0px;
        }
        .flashInner
        {
            position: relative;
            left: -50%; 
        }
        .error 
        {
            padding: 20px; 
            padding-right: 80px;
            padding-left: 80px;
            background-color: #c22c21;
            color: #f0aaa5; 
        }
        .errorbutton 
        {
            background-color: #c22c21;
            color: white;
            border-style: none;
        }
        .success 
        {
            padding: 20px; 
            padding-right: 80px;
            padding-left: 80px;
            background-color: #28660d;
            color: #c2edaf; 
        }
        .successbutton 
        {
            background-color: #28660d;
            color: white;
            border-style: none;
        }
        </style>
</head>
<body>


    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class=flashes>
            {% for category, message in messages %}
                <div class="flash">
                    <div class="flashInner">
                        <p  class="{{ category }}">{{ message }}

                            <button 
                                id="close" 
                                onclick="this.parentNode.parentNode.remove(); return false;"
                                class="{{category}}button"
                                >
                                x
                            </button>     
                        </p>
                         
                    </div>
                </div>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}   






    <div class="website">
        <h1 style="color:rgb(77, 151, 77);">Pagrabs.xyz</h1>
        <div class="navigation">
            <a class="link {% block izsoles %}{% endblock %}" href="{{url_for('home.index')}}">
                Izsoles
            </a>
            {% if current_user.name %}
                {% if current_user.isVerified %}
                    <a class="link {% block ievietot %}{% endblock %}" href="{{url_for('listing.new')}}">
                        Ievietot
                    </a>
                    <a class="link {% block pirkumi %}{% endblock %}" href="{{url_for('listing.myHistory')}}">
                        Pirkumi
                    </a>
                {% endif %}

                <a class="linkleft" href="/logout">
                    iziet 
                </a>
                <a class="linkleft {% block profils %}{% endblock %}" href="{{url_for('user.profile')}}">
                    Profils
                </a>
                {% if current_user.isAdmin %}
                <a class="linkleft" href="{{url_for('admin.adminPanel')}}">
                    Admin Panel
                </a>
                {% endif %}
                <a class="profileInfo">
                    {{current_user.username}}
                </a>
            {% else %}
                <a class="linkleft {% block registreties %}{% endblock %}" href="{{url_for('auth.register')}}">
                    reģistrēties
                </a>
                <a class="linkleft {% block pieslegties %}{% endblock %}" href="{{url_for('auth.login')}}">
                    pieslēgties
                </a>
            {% endif %}
        </div>
    
        <div class="content">
            <h1>
                <center>
                    {% block title %}{% endblock %}
                </center>
            </h1>
            {% block content %} 
            {% endblock %}
        </div>
    </div>
</body>
</html>