routes/user.py
from flask import Blueprint, render_template,flash, url_for, redirect, request
from models import Listing, pytz, current_user, db
user = Blueprint("user", __name__, static_folder="static", template_folder="templates")

@user.route("/profils")
def profile():
    if not current_user.is_authenticated:
        flash("Tikai pieslēgti lietotāji var apskatīt savu profilu!",'error')
        return redirect(url_for("home.index"))
    ongoing = []
    for listing in Listing.query.filter_by(userID=current_user.id, auctionStatus=2).all():
        ongoing.append(listing)
    for listing in Listing.query.filter_by(userID=current_user.id, auctionStatus=1).all():
        ongoing.append(listing)
    return render_template("user/profile.html", 
                           waitingListings = Listing.query.filter_by(userID=current_user.id, auctionStatus=0).all(),
                           ongoingListings = ongoing,
                           endedListings = Listing.query.filter_by(userID=current_user.id, auctionStatus=3).all(),
                           listings = Listing.query.filter_by(userID=current_user.id)
                           )


@user.route("/add-bank",methods=['POST'])
def addBank():
    if not current_user.is_authenticated:
        flash('pieslēdzies lai darītu šo darbību!','error')
        return redirect(url_for("auth.login"))
    
    current_user.bankAccount = request.form['bankAccount']
    current_user.bankName= request.form['bankName']
    current_user.bankSurname = request.form['bankSurname']
    db.session.commit()
    return redirect(url_for('user.profile'))

@user.route("/profils/rediget")
def edit_profile():
    if not current_user.is_authenticated:
        flash("Dumiķi... nevari rediģēt savu kontu, ja neesi pieslēdzies :D",'error')
        return redirect(url_for("home.index"))
    return render_template("user/edit.html", user = current_user)

templates/user/edit.html
{% extends 'template.html' %}


{% block profils %}active{% endblock %}

{% block content %} 
<style>
    .formInput 
    {
        margin-bottom: 5px;
        width: 50%;
        height:50px;
        font-size:larger; 
        border-radius: 5px;
    }
    .formButton
    {
        margin-bottom: 5px;
        width: 20%;
        height:50px;
        text-align: center; 
        font-size:larger; 
        border-radius: 5px;  
    }

    .warning
    {
        background-color: rgb(255, 94, 94);
        color:rgb(60, 0, 0);
        width: 50%;
        padding: 10px;
        margin-top: 20px;
        border-radius: 8px;
    }
</style>
<center>
    <h1>Rediģēt profilu</h1>
    <form method="POST" action="/verify">
        <h2>pamata info</h2>
        Lietotājvārds<br>
        <input 
            class="formInput"
            maxlength="24"
            type="text" 
            placeholder="{{user.username}}" 
            name="code" 
            value="{{ request.form['username'] }}" 
            required> <br>
        Vārds<br>
        <input 
            class="formInput"
            maxlength="24"
            type="text" 
            placeholder="{{user.name}}" 
            name="code" 
            value="{{ request.form['name'] }}" 
            required> <br>
        Uzvārds<br>
        <input 
            class="formInput"
            maxlength="24"
            type="text" 
            placeholder="{{user.surname}}" 
            name="code" 
            value="{{ request.form['surname'] }}" 
            required> <br>
        <input class="formButton" type="submit" value="saglabāt">
    </form>
    <form method="POST" action="/verify">
        <h2>Bankas info</h2>
        Konta numurs<br>
        <input 
            class="formInput"
            maxlength="25"
            type="text" 
            placeholder="{{user.bankAccount}}" 
            name="code" 
            value="{{ request.form['bank'] }}" 
            required> <br>
        Konta īpašnieka vārds<br>
        <input 
            class="formInput"
            maxlength="64"
            type="text" 
            placeholder="{{user.bankName}}" 
            name="code" 
            value="{{ request.form['bankName'] }}" 
            required> <br>
        Konta īpašnieka uzvārds<br>
        <input 
            class="formInput"
            maxlength="64"
            type="text" 
            placeholder="{{user.bankSurname}}" 
            name="code" 
            value="{{ request.form['bankSurname'] }}" 
            required> <br>
        <input class="formButton" type="submit" value="Saglabāt banku">
    </form>
</center>
{% endblock %}

templates/user/profile.html
{% extends 'template.html' %}


{% block profils %}active{% endblock %}

{% block content %} 
<style>
    .formInput 
    {
        margin-bottom: 5px;
        width: 50%;
        height:50px;
        font-size:larger; 
        border-radius: 5px;
    }
    .formButton
    {
        margin-bottom: 5px;
        width: 20%;
        height:50px;
        text-align: center; 
        font-size:larger; 
        border-radius: 5px;  
    }

    .warning
    {
        background-color: rgb(255, 94, 94);
        color:rgb(60, 0, 0);
        width: 50%;
        padding: 10px;
        margin-top: 20px;
        border-radius: 8px;
    }
    a
    {
        text-decoration: none;
        color: #ADA8BE;
    }
    .listing
    {
        background-color: transparent;
        width: 80%;
        height: 256px;
        margin-top: 5%;
        height: 150%;
    }

    hr
    {
        border-bottom:none;
        border-left: none;
        border-right: none;
        border-top-width: 3px;
        border-top-color: black;
        background-color: black;
    }

    .listingImage
    {
        float: left; 
        width: 256px;
    }

    .listingInfo
    {
        overflow: hidden; 
        padding-left: 2vw;
        padding-bottom: 1vh;
        text-align:left;
        text-decoration: none;
    }
    .name {
        margin-top: 0px;
    }
    .startPrice
    {
        color: #A28497;
        text-decoration: none;
    }

    .priceIncrease
    {
        color: #A28497;
        text-decoration: none;
    }

    .auctionDate
    {
        color: #A28497; 
        text-decoration: none;
    }

    .info
    {
        color: #A28497;
        text-decoration: none;  
    }

    .description
    {
        word-break:keep-all;
        padding-bottom: 5px;
        border-bottom: 1px solid rgb(150, 150, 150);
    }
    .joinAuction
    {
        padding: 15px;
        margin-top: 10px;
        width: fit-content;
        background-color:#4267B2;
        color: white;
    }
    .joinAuction:hover
    {
        background-color:#1d489e;
    }
    .joinAuction:active
    {
        background-color:#0e388b;
    }
    .overlay {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
      }
      
      .listing-info {
        background-color: white;
        padding: 20px;
        border-radius: 5px;
        text-align: center;
        width: 90vw;
        min-height: 50%;
      }
</style>
<center>
    <h1>{{current_user.username}}</h1>
    <span><a href="{{url_for('user.edit_profile')}}">rediģēt profilu</a></span><br>
    {% if not current_user.isVerified %}
        Tu neesi verificēts!<br>
        <form method="POST" action="/verify">
            <h2>Verificējies!</h2>
            <input 
                class="formInput"
                maxlength="12"
                type="text" 
                placeholder="Verifikācijas kods" 
                name="code" 
                value="{{ request.form['code'] }}" 
                required> <br>
            <input class="formButton" type="submit" value="verificēties">
        </form>
        <br>
        <br>
        <h3>Verifikācijas kods: {{current_user.verificationCode}}</h3><br>
    {% else %}
        {% if not current_user.bankAccount %}
            <h4>Lai varētu saņemt naudu par saviem ievietojumiem, vajag pievienot savu bankas informāciju!</h4>
            <form method="POST" action="/lietotajs/add-bank">
                <h2>Pievienot banku!</h2>
                <input 
                    class="formInput"
                    maxlength="25"
                    type="text" 
                    placeholder="Konta numurs" 
                    name="bankAccount" 
                    value="{{ request.form['bankAccount'] }}" 
                    required> <br>
                
                <input 
                    class="formInput"
                    maxlength="64"
                    type="text" 
                    placeholder="Konta īpašnieka vārds" 
                    name="bankName" 
                    value="{{ request.form['bankName'] }}" 
                    required> <br>

                <input 
                    class="formInput"
                    maxlength="64"
                    type="text" 
                    placeholder="Konta īpašnieka uzvārds" 
                    name="bankSurname" 
                    value="{{ request.form['bankSurname'] }}" 
                    required> <br>
                <input class="formButton" type="submit" value="pievienot">
            </form> 
        {% endif %}
    {% endif %}
    <hr style="width: 60%;">

    <h2>Mani ievietojumi</h2>
    {% if not ongoingListings and not waitingListings and not endedListings %}
        <h3>Tu vēl neko neesi ievietojis!</h3>
    {% endif %}
    {% if endedListings or waitingListings or ongoingListings %}
        {% if not current_user.bankAccount %}

        <div class="warning">
            <h3>Brīdinājums</h3>
            Nesaņemsi naudu par izsoli, ja nebūs pievienota bankas<br>
            konta informācija. Pievieno to savā profilā!
        </div>
        {% endif %}
    {% endif %}
    {% if ongoingListings %}
        <h3>Šobrīd tiek izsolīts</h3>
        {% for listing in ongoingListings %}
            <div id="listing{{listing.id}}">
                nosaukums: {{listing.name}}<br>
                datums: {{listing.date}}<br>
                cena: {{listing.price}}
            </div><hr width="30%"><br>
        {% endfor %}
    {% endif %}

    {% if waitingListings %}
        <h3>Izsoles kas gaida</h3>
        {% for listing in waitingListings %}
            <div id="listing{{listing.id}}">
                nosaukums: {{listing.name}}<br>
                datums: {{listing.date}}<br>
                cena: {{listing.price}}
            </div><hr width="30%"><br>
        {% endfor %}
    {% endif %}

    {% if endedListings %}
    <h3>Beigušās izsoles</h3>
        {% for listing in endedListings %}
            <div id="listing{{listing.id}}">
                nosaukums: {{listing.name}}<br>
                datums: {{listing.date}}<br>
                cena: {{listing.price}}
            </div><hr width="30%"><br>
        {% endfor %}
    {% endif %}

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            {% for listing in listings %}
                document.getElementById("listing{{listing.id}}").addEventListener("click", function() {
                    var overlay = document.createElement("div");
                    overlay.id = "overlay{{listing.id}}";
                    overlay.classList.add("overlay");
    
                    var listingInfo = document.createElement("div");
                    listingInfo.classList.add("listing-info");
    

    
                    // Listing name
                    var listingName = document.createElement("h1");
                    listingName.classList.add("name");
                    listingName.textContent = "{{listing.name}}";
                    listingInfo.appendChild(listingName);
    
                    // Listing description
                    var listingDescription = document.createElement("h3");
                    listingDescription.classList.add("description");
                    listingDescription.textContent = "{{listing.description}}";
                    listingInfo.appendChild(listingDescription);
    
                    // Listing image
                    var listingImage = document.createElement("img");
                    listingImage.src = "{{listing.image}}";
                    listingImage.style.width = "30%";
                    listingImage.style.objectFit = "cover";
                    listingInfo.appendChild(listingImage);

                    {% if current_user.id == listing.userID or current_user.isAdmin %}
                        var br = document.createElement("br");
                        listingInfo.appendChild(br);


                        var link = document.createElement("a");
                        link.href = "/prece/rediget/{{listing.id}}";
                        link.textContent = "rediģēt";
                        listingInfo.appendChild(link);  
                    {% endif %}

                    overlay.appendChild(listingInfo);
                    document.body.appendChild(overlay);
    
                    overlay.addEventListener("click", function(e) {
                        if (e.target === overlay) {
                            document.body.removeChild(overlay);
                        }
                    });
                });
            {% endfor %}
        });
    </script>
</center>
{% endblock %}